<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.WebhooksManagement.Domain</AssemblyName>
		<PackageId>Miwen.Abp.WebhooksManagement.Domain</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AutoMapper" />
		<PackageReference Include="Volo.Abp.Caching" />
		<PackageReference Include="Volo.Abp.Ddd.Domain" />
		<PackageReference Include="Polly" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Miwen.Abp.WebhooksManagement.Domain.Shared\Miwen.Abp.WebhooksManagement.Domain.Shared.csproj" />
		<ProjectReference Include="..\Miwen.Abp.Webhooks\Miwen.Abp.Webhooks.csproj" />
	</ItemGroup>

</Project>
