<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>Nullable</WarningsAsErrors>
		<AssemblyName>Miwen.Abp.AuditLogging.IP.Location</AssemblyName>
		<PackageId>Miwen.Abp.AuditLogging.IP.Location</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\common\Miwen.Abp.IP.Location\Miwen.Abp.IP.Location.csproj" />
		<ProjectReference Include="..\Miwen.Abp.AuditLogging\Miwen.Abp.AuditLogging.csproj" />
	</ItemGroup>

</Project>
