<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.AspNetCore.Mvc.Wrapper</AssemblyName>
		<PackageId>Miwen.Abp.AspNetCore.Mvc.Wrapper</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Miwen\Abp\AspNetCore\Mvc\Wrapper\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Miwen\Abp\AspNetCore\Mvc\Wrapper\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\common\Miwen.Abp.AspNetCore.Wrapper\Miwen.Abp.AspNetCore.Wrapper.csproj" />
	  <ProjectReference Include="..\..\common\Miwen.Abp.Wrapper\Miwen.Abp.Wrapper.csproj" />
	</ItemGroup>

</Project>
