<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.UI.Navigation.VueVbenAdmin</AssemblyName>
		<PackageId>Miwen.Abp.UI.Navigation.VueVbenAdmin</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Data" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\framework\navigation\Miwen.Abp.UI.Navigation\Miwen.Abp.UI.Navigation.csproj" />
		<ProjectReference Include="..\Miwen.Platform.Domain\Miwen.Platform.Domain.csproj" />
	</ItemGroup>

</Project>
