<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.BackgroundTasks</AssemblyName>
		<PackageId>Miwen.Abp.BackgroundTasks</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Miwen\Abp\BackgroundTasks\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Miwen\Abp\BackgroundTasks\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Auditing" />
		<PackageReference Include="Volo.Abp.BackgroundJobs.Abstractions" />
		<PackageReference Include="Volo.Abp.BackgroundWorkers" />
		<PackageReference Include="Volo.Abp.Caching" />
		<PackageReference Include="Volo.Abp.Guids" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Miwen.Abp.BackgroundTasks.Abstractions\Miwen.Abp.BackgroundTasks.Abstractions.csproj" />
	</ItemGroup>

</Project>
