<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.Notifications.Emailing</AssemblyName>
		<PackageId>Miwen.Abp.Notifications.Emailing</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Emailing" />
		<PackageReference Include="Markdig" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\identity\Miwen.Abp.Identity.Domain\Miwen.Abp.Identity.Domain.csproj" />
		<ProjectReference Include="..\Miwen.Abp.Notifications\Miwen.Abp.Notifications.csproj" />
	</ItemGroup>

</Project>
