<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
		<AssemblyName>Miwen.Abp.Webhooks</AssemblyName>
		<PackageId>Miwen.Abp.Webhooks</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Volo.Abp.BackgroundJobs.Abstractions" />
		<PackageReference Include="Volo.Abp.Features" />
		<PackageReference Include="Volo.Abp.Guids" />
		<PackageReference Include="Volo.Abp.Http.Client" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Miwen.Abp.Webhooks.Core\Miwen.Abp.Webhooks.Core.csproj" />
	</ItemGroup>

</Project>
