<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\configureawait.props" />
  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Miwen.Abp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miwen.Abp.Domain\Miwen.Abp.Domain.csproj" />
    <ProjectReference Include="..\Miwen.Abp.Application.Contracts\Miwen.Abp.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AutoMapper" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" />
    <PackageReference Include="Volo.Abp.Account.Application" />
    <PackageReference Include="Volo.Abp.Identity.Application" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" />
  </ItemGroup>

</Project>
