<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<TargetFramework>net8.0</TargetFramework>
		<AssemblyName>Miwen.Abp.OAuth.Github</AssemblyName>
		<PackageId>Miwen.Abp.OAuth.Github</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Miwen\Abp\OAuth\Github\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Miwen\Abp\OAuth\Github\Localization\Resources\*.json" />
	</ItemGroup>
		
	<ItemGroup>
	  <ProjectReference Include="..\Miwen.Abp.OAuth\Miwen.Abp.OAuth.csproj" />
	</ItemGroup>
	
	
</Project>
