<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.TaskManagement.Domain.Shared</AssemblyName>
		<PackageId>Miwen.Abp.TaskManagement.Domain.Shared</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Miwen\Abp\TaskManagement\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Miwen\Abp\TaskManagement\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Validation" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Miwen.Abp.BackgroundTasks.Abstractions\Miwen.Abp.BackgroundTasks.Abstractions.csproj" />
	</ItemGroup>

</Project>
