<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.OpenApi.Authorization</AssemblyName>
		<PackageId>Miwen.Abp.OpenApi.Authorization</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\common\Miwen.Abp.Wrapper\Miwen.Abp.Wrapper.csproj" />
	  <ProjectReference Include="..\Miwen.Abp.OpenApi\Miwen.Abp.OpenApi.csproj" />
	</ItemGroup>

</Project>
