<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\configureawait.props" />
  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Miwen.Abp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miwen.Abp.Application.Contracts\Miwen.Abp.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" />
    <PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" />
    <PackageReference Include="Volo.Abp.SettingManagement.HttpApi" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Identity.HttpApi" />
    <PackageReference Include="Volo.Abp.Account.HttpApi" />
    <PackageReference Include="Volo.Abp.TenantManagement.HttpApi" />
  </ItemGroup>

</Project>
