<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.DataProtectionManagement.Domain</AssemblyName>
		<PackageId>Miwen.Abp.DataProtectionManagement.Domain</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AutoMapper" />
		<PackageReference Include="Volo.Abp.Ddd.Domain" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\framework\data-protection\Miwen.Abp.DataProtection\Miwen.Abp.DataProtection.csproj" />
	  <ProjectReference Include="..\Miwen.Abp.DataProtectionManagement.Domain.Shared\Miwen.Abp.DataProtectionManagement.Domain.Shared.csproj" />
	</ItemGroup>

</Project>
