<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.OpenIddict.LinkUser</AssemblyName>
		<PackageId>Miwen.Abp.OpenIddict.LinkUser</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Miwen\Abp\OpenIddict\LinkUser\Localization\Resources\*.json" />
	</ItemGroup>
	
	<ItemGroup>
		<EmbeddedResource Include="Miwen\Abp\OpenIddict\LinkUser\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.OpenIddict.AspNetCore" />
	</ItemGroup>

</Project>
