<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>0.0.1</Version>
	<Authors>Miwen</Authors>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
	  <PackageProjectUrl>https://github.com/ksdaylight/abp-react-admin</PackageProjectUrl>
	  <PackageOutputPath>$(SolutionDir)LocalNuget</PackageOutputPath>
	  <PackageVersion>0.0.1</PackageVersion>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <RepositoryType>git</RepositoryType>
	  <RepositoryUrl>https://github.com/ksdaylight/abp-react-admin</RepositoryUrl>
	  <GeneratePackageOnBuild Condition="$(AssemblyName.StartsWith('Miwen'))">true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
	  <Compile Remove="LocalNuget\**" />
	  <EmbeddedResource Remove="LocalNuget\**" />
	  <None Remove="LocalNuget\**" />
  </ItemGroup>

  <ItemGroup>
	  <Compile Remove="Logs\**" />
	  <Content Remove="Logs\**" />
	  <EmbeddedResource Remove="Logs\**" />
	  <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
	  <Compile Remove="Modules\**" />
	  <EmbeddedResource Remove="Modules\**" />
	  <None Remove="Modules\**" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <OutputPath>$(SolutionDir)LocalNuget</OutputPath>
  </PropertyGroup>

</Project>