<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.DataProtectionManagement.EntityFrameworkCore</AssemblyName>
		<PackageId>Miwen.Abp.DataProtectionManagement.EntityFrameworkCore</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\framework\data-protection\Miwen.Abp.DataProtection.EntityFrameworkCore\Miwen.Abp.DataProtection.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\Miwen.Abp.DataProtectionManagement.Domain\Miwen.Abp.DataProtectionManagement.Domain.csproj" />
	</ItemGroup>

</Project>
