<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="..\..\common.secrets.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Miwen.MicroService.Applications.Single</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DistributedLock.Redis" />
		<PackageReference Include="Elsa.Activities.Email" />
		<PackageReference Include="Elsa.Activities.Http" />
		<PackageReference Include="Elsa.Activities.UserTask" />
		<PackageReference Include="Elsa.Activities.Temporal.Quartz" />
		<!--<PackageReference Include="Elsa.Designer.Components.Web" />-->
		<PackageReference Include="Elsa.Webhooks.Api" />
		<PackageReference Include="Volo.Abp.MailKit" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" />
		<PackageReference Include="OpenIddict.Validation.DataProtection" />
		<PackageReference Include="OpenIddict.Server.DataProtection" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Enrichers.Environment" />
		<PackageReference Include="Serilog.Enrichers.Assembly" />
		<PackageReference Include="Serilog.Enrichers.Process" />
		<PackageReference Include="Serilog.Enrichers.Thread" />
		<PackageReference Include="Serilog.Settings.Configuration" />
		<PackageReference Include="Serilog.Sinks.Elasticsearch" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Quartz.Serialization.Json" />
		<PackageReference Include="Volo.Abp.Account.Web.OpenIddict" />
		<!--<PackageReference Include="Volo.Abp.Account.Web.IdentityServer" />-->
		<PackageReference Include="Volo.Abp.AspNetCore.Serilog" />
		<PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy" />
		<PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic" />
		<PackageReference Include="Volo.Abp.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Volo.Abp.Autofac" />
		<PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" />
		<PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" />
		<PackageReference Include="Volo.Abp.FeatureManagement.Application" />
		<PackageReference Include="Volo.Abp.FeatureManagement.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.FeatureManagement.HttpApi" />
		<PackageReference Include="Volo.Abp.PermissionManagement.Application" />
		<PackageReference Include="Volo.Abp.PermissionManagement.Domain.Identity" />
		<PackageReference Include="Volo.Abp.PermissionManagement.Domain.IdentityServer" />
		<PackageReference Include="Volo.Abp.PermissionManagement.Domain.OpenIddict" />
		<PackageReference Include="Volo.Abp.PermissionManagement.HttpApi" />
		<PackageReference Include="Volo.Abp.Identity.AspNetCore" />
		<PackageReference Include="Volo.Abp.Imaging.ImageSharp" />
		<!--<PackageReference Include="Volo.Abp.IdentityServer.EntityFrameworkCore" />-->
		<PackageReference Include="Volo.Abp.SettingManagement.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.PermissionManagement.EntityFrameworkCore" />
		<PackageReference Include="Volo.Abp.OpenIddict.EntityFrameworkCore" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\framework\auditing\Miwen.Abp.AuditLogging.EntityFrameworkCore\Miwen.Abp.AuditLogging.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\framework\auditing\Miwen.Abp.AuditLogging.IP.Location\Miwen.Abp.AuditLogging.IP.Location.csproj" />
		<ProjectReference Include="..\..\framework\auditing\Miwen.Abp.AuditLogging\Miwen.Abp.AuditLogging.csproj" />
		<ProjectReference Include="..\..\framework\authorization\Miwen.Abp.Authorization.OrganizationUnits\Miwen.Abp.Authorization.OrganizationUnits.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.AspNetCore.HttpOverrides\Miwen.Abp.AspNetCore.HttpOverrides.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.ExceptionHandling.Emailing\Miwen.Abp.ExceptionHandling.Emailing.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.ExceptionHandling\Miwen.Abp.ExceptionHandling.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.Features.LimitValidation.Redis.Client\Miwen.Abp.Features.LimitValidation.Redis.Client.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.Features.LimitValidation.Redis\Miwen.Abp.Features.LimitValidation.Redis.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.Features.LimitValidation\Miwen.Abp.Features.LimitValidation.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.Http.Client.Wrapper\Miwen.Abp.Http.Client.Wrapper.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.IdGenerator\Miwen.Abp.IdGenerator.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.RealTime\Miwen.Abp.RealTime.csproj" />
		<ProjectReference Include="..\..\framework\common\Miwen.Abp.Wrapper\Miwen.Abp.Wrapper.csproj" />
		<ProjectReference Include="..\..\framework\dynamic-queryable\Miwen.Abp.Dynamic.Queryable.Application.Contracts\Miwen.Abp.Dynamic.Queryable.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\framework\dynamic-queryable\Miwen.Abp.Dynamic.Queryable.Application\Miwen.Abp.Dynamic.Queryable.Application.csproj" />
		<ProjectReference Include="..\..\framework\dynamic-queryable\Miwen.Abp.Dynamic.Queryable.HttpApi\Miwen.Abp.Dynamic.Queryable.HttpApi.csproj" />
		<ProjectReference Include="..\..\framework\dynamic-queryable\Miwen.Linq.Dynamic.Queryable\Miwen.Linq.Dynamic.Queryable.csproj" />
		<ProjectReference Include="..\..\framework\exporter\Miwen.Abp.Exporter.MiniExcel\Miwen.Abp.Exporter.MiniExcel.csproj" />
		<ProjectReference Include="..\..\framework\features\Miwen.Abp.FeatureManagement.Client\Miwen.Abp.FeatureManagement.Client.csproj" />
		<ProjectReference Include="..\..\framework\localization\Miwen.Abp.AspNetCore.Mvc.Localization\Miwen.Abp.AspNetCore.Mvc.Localization.csproj" />
		<ProjectReference Include="..\..\framework\localization\Miwen.Abp.Localization.CultureMap\Miwen.Abp.Localization.CultureMap.csproj" />
		<ProjectReference Include="..\..\framework\localization\Miwen.Abp.Localization.Persistence\Miwen.Abp.Localization.Persistence.csproj" />
		<ProjectReference Include="..\..\framework\logging\Miwen.Abp.Logging.Serilog.Elasticsearch\Miwen.Abp.Logging.Serilog.Elasticsearch.csproj" />
		<ProjectReference Include="..\..\framework\logging\Miwen.Abp.Logging\Miwen.Abp.Logging.csproj" />
		<ProjectReference Include="..\..\framework\logging\Miwen.Abp.Serilog.Enrichers.Application\Miwen.Abp.Serilog.Enrichers.Application.csproj" />
		<ProjectReference Include="..\..\framework\logging\Miwen.Abp.Serilog.Enrichers.UniqueId\Miwen.Abp.Serilog.Enrichers.UniqueId.csproj" />
		<ProjectReference Include="..\..\framework\mvc\Miwen.Abp.AspNetCore.Mvc.Idempotent.Wrapper\Miwen.Abp.AspNetCore.Mvc.Idempotent.Wrapper.csproj" />
		<ProjectReference Include="..\..\framework\mvc\Miwen.Abp.AspNetCore.Mvc.Wrapper\Miwen.Abp.AspNetCore.Mvc.Wrapper.csproj" />
		<ProjectReference Include="..\..\framework\navigation\Miwen.Abp.UI.Navigation\Miwen.Abp.UI.Navigation.csproj" />
		<ProjectReference Include="..\..\framework\open-api\Miwen.Abp.OpenApi.Authorization\Miwen.Abp.OpenApi.Authorization.csproj" />
		<ProjectReference Include="..\..\framework\open-api\Miwen.Abp.OpenApi\Miwen.Abp.OpenApi.csproj" />
		<ProjectReference Include="..\..\framework\settings\Miwen.Abp.SettingManagement.Application.Contracts\Miwen.Abp.SettingManagement.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\framework\tenants\Miwen.Abp.MultiTenancy.Editions\Miwen.Abp.MultiTenancy.Editions.csproj" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\migrations\Miwen.MicroService.Applications.Single.EntityFrameworkCore\Miwen.MicroService.Applications.Single.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\account\Miwen.Abp.Account.Application.Contracts\Miwen.Abp.Account.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\account\Miwen.Abp.Account.Application\Miwen.Abp.Account.Application.csproj" />
		<ProjectReference Include="..\..\modules\account\Miwen.Abp.Account.HttpApi\Miwen.Abp.Account.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\account\Miwen.Abp.Account.Templates\Miwen.Abp.Account.Templates.csproj" />
    <ProjectReference Include="..\..\modules\auditing\Miwen.Abp.Auditing.Application.Contracts\Miwen.Abp.Auditing.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\auditing\Miwen.Abp.Auditing.Application\Miwen.Abp.Auditing.Application.csproj" />
		<ProjectReference Include="..\..\modules\auditing\Miwen.Abp.Auditing.HttpApi\Miwen.Abp.Auditing.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\caching-management\Miwen.Abp.CachingManagement.Application.Contracts\Miwen.Abp.CachingManagement.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\caching-management\Miwen.Abp.CachingManagement.Application\Miwen.Abp.CachingManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\caching-management\Miwen.Abp.CachingManagement.Domain\Miwen.Abp.CachingManagement.Domain.csproj" />
		<ProjectReference Include="..\..\modules\caching-management\Miwen.Abp.CachingManagement.HttpApi\Miwen.Abp.CachingManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\caching-management\Miwen.Abp.CachingManagement.StackExchangeRedis\Miwen.Abp.CachingManagement.StackExchangeRedis.csproj" />
		<ProjectReference Include="..\..\modules\data-protection\Miwen.Abp.DataProtectionManagement.Application\Miwen.Abp.DataProtectionManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\data-protection\Miwen.Abp.DataProtectionManagement.EntityFrameworkCore\Miwen.Abp.DataProtectionManagement.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\data-protection\Miwen.Abp.DataProtectionManagement.HttpApi\Miwen.Abp.DataProtectionManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Activities.BlobStoring\Miwen.Abp.Elsa.Activities.BlobStoring.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Activities.Emailing\Miwen.Abp.Elsa.Activities.Emailing.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Activities.IM\Miwen.Abp.Elsa.Activities.IM.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Activities.Notifications\Miwen.Abp.Elsa.Activities.Notifications.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Activities.Sms\Miwen.Abp.Elsa.Activities.Sms.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Activities.Webhooks\Miwen.Abp.Elsa.Activities.Webhooks.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Activities\Miwen.Abp.Elsa.Activities.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.EntityFrameworkCore.PostgreSql\Miwen.Abp.Elsa.EntityFrameworkCore.PostgreSql.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.EntityFrameworkCore\Miwen.Abp.Elsa.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa.Server\Miwen.Abp.Elsa.Server.csproj" />
		<ProjectReference Include="..\..\modules\elsa\Miwen.Abp.Elsa\Miwen.Abp.Elsa.csproj" />
		<ProjectReference Include="..\..\modules\feature-management\Miwen.Abp.FeatureManagement.Application\Miwen.Abp.FeatureManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\feature-management\Miwen.Abp.FeatureManagement.HttpApi\Miwen.Abp.FeatureManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.Application.Contracts\Miwen.Abp.Identity.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.Application\Miwen.Abp.Identity.Application.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.AspNetCore.Session\Miwen.Abp.Identity.AspNetCore.Session.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.Domain.Shared\Miwen.Abp.Identity.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.Domain\Miwen.Abp.Identity.Domain.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.EntityFrameworkCore\Miwen.Abp.Identity.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.HttpApi\Miwen.Abp.Identity.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.Notifications\Miwen.Abp.Identity.Notifications.csproj" />
		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.OrganizaztionUnits\Miwen.Abp.Identity.OrganizaztionUnits.csproj" />
		

		<ProjectReference Include="..\..\modules\identity\Miwen.Abp.Identity.Session.AspNetCore\Miwen.Abp.Identity.Session.AspNetCore.csproj" />
		<ProjectReference Include="..\..\modules\localization-management\Miwen.Abp.LocalizationManagement.Application.Contracts\Miwen.Abp.LocalizationManagement.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\localization-management\Miwen.Abp.LocalizationManagement.Application\Miwen.Abp.LocalizationManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\localization-management\Miwen.Abp.LocalizationManagement.Domain.Shared\Miwen.Abp.LocalizationManagement.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\localization-management\Miwen.Abp.LocalizationManagement.Domain\Miwen.Abp.LocalizationManagement.Domain.csproj" />
		<ProjectReference Include="..\..\modules\localization-management\Miwen.Abp.LocalizationManagement.EntityFrameworkCore\Miwen.Abp.LocalizationManagement.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\localization-management\Miwen.Abp.LocalizationManagement.HttpApi\Miwen.Abp.LocalizationManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.AspNetCore.Session\Miwen.Abp.OpenIddict.AspNetCore.Session.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.AspNetCore\Miwen.Abp.OpenIddict.AspNetCore.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.IM.SignalR\Miwen.Abp.IM.SignalR.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.IM\Miwen.Abp.IM.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.MessageService.Application.Contracts\Miwen.Abp.MessageService.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.MessageService.Application\Miwen.Abp.MessageService.Application.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.MessageService.Domain.Shared\Miwen.Abp.MessageService.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.MessageService.Domain\Miwen.Abp.MessageService.Domain.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.MessageService.EntityFrameworkCore\Miwen.Abp.MessageService.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\realtime-message\Miwen.Abp.MessageService.HttpApi\Miwen.Abp.MessageService.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.ExceptionHandling.Notifications\Miwen.Abp.ExceptionHandling.Notifications.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.Common\Miwen.Abp.Notifications.Common.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.Core\Miwen.Abp.Notifications.Core.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.Emailing\Miwen.Abp.Notifications.Emailing.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.SignalR\Miwen.Abp.Notifications.SignalR.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.Application.Contracts\Miwen.Abp.Notifications.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.Application\Miwen.Abp.Notifications.Application.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.Domain.Shared\Miwen.Abp.Notifications.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.Domain\Miwen.Abp.Notifications.Domain.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.EntityFrameworkCore\Miwen.Abp.Notifications.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\realtime-notifications\Miwen.Abp.Notifications.HttpApi\Miwen.Abp.Notifications.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.Application.Contracts\Miwen.Abp.OpenIddict.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.Application\Miwen.Abp.OpenIddict.Application.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.HttpApi\Miwen.Abp.OpenIddict.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.LinkUser\Miwen.Abp.OpenIddict.LinkUser.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.Sms\Miwen.Abp.OpenIddict.Sms.csproj" />
		<ProjectReference Include="..\..\modules\openIddict\Miwen.Abp.OpenIddict.Portal\Miwen.Abp.OpenIddict.Portal.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.Application.Contracts\Miwen.Abp.OssManagement.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.Application\Miwen.Abp.OssManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.Domain.Shared\Miwen.Abp.OssManagement.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.Domain\Miwen.Abp.OssManagement.Domain.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.FileSystem\Miwen.Abp.OssManagement.FileSystem.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.Imaging\Miwen.Abp.OssManagement.Imaging.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.Minio\Miwen.Abp.OssManagement.Minio.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.HttpApi\Miwen.Abp.OssManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\oss-management\Miwen.Abp.OssManagement.SettingManagement\Miwen.Abp.OssManagement.SettingManagement.csproj" />
		<ProjectReference Include="..\..\modules\permissions-management\Miwen.Abp.PermissionManagement.Application\Miwen.Abp.PermissionManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\permissions-management\Miwen.Abp.PermissionManagement.Domain.OrganizationUnits\Miwen.Abp.PermissionManagement.Domain.OrganizationUnits.csproj" />
		<ProjectReference Include="..\..\modules\permissions-management\Miwen.Abp.PermissionManagement.HttpApi\Miwen.Abp.PermissionManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Abp.UI.Navigation.VueVbenAdmin\Miwen.Abp.UI.Navigation.VueVbenAdmin.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.Application.Contracts\Miwen.Platform.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.Application\Miwen.Platform.Application.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.Domain.Shared\Miwen.Platform.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.Domain\Miwen.Platform.Domain.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.EntityFrameworkCore\Miwen.Platform.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.HttpApi\Miwen.Platform.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.Settings.VueVbenAdmin\Miwen.Platform.Settings.VueVbenAdmin.csproj" />
		<ProjectReference Include="..\..\modules\platform\Miwen.Platform.Theme.VueVbenAdmin\Miwen.Platform.Theme.VueVbenAdmin.csproj" />
		<ProjectReference Include="..\..\modules\saas\Miwen.Abp.Saas.Application.Contracts\Miwen.Abp.Saas.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\saas\Miwen.Abp.Saas.Domain.Shared\Miwen.Abp.Saas.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\saas\Miwen.Abp.Saas.Domain\Miwen.Abp.Saas.Domain.csproj" />
		<ProjectReference Include="..\..\modules\saas\Miwen.Abp.Saas.Application\Miwen.Abp.Saas.Application.csproj" />
		<ProjectReference Include="..\..\modules\saas\Miwen.Abp.Saas.EntityFrameworkCore\Miwen.Abp.Saas.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\saas\Miwen.Abp.Saas.HttpApi\Miwen.Abp.Saas.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\settings\Miwen.Abp.SettingManagement.Application\Miwen.Abp.SettingManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\settings\Miwen.Abp.SettingManagement.HttpApi\Miwen.Abp.SettingManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.Abstractions\Miwen.Abp.BackgroundTasks.Abstractions.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.Activities\Miwen.Abp.BackgroundTasks.Activities.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.DistributedLocking\Miwen.Abp.BackgroundTasks.DistributedLocking.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.EventBus\Miwen.Abp.BackgroundTasks.EventBus.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.ExceptionHandling\Miwen.Abp.BackgroundTasks.ExceptionHandling.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.Jobs\Miwen.Abp.BackgroundTasks.Jobs.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.Notifications\Miwen.Abp.BackgroundTasks.Notifications.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks.Quartz\Miwen.Abp.BackgroundTasks.Quartz.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.BackgroundTasks\Miwen.Abp.BackgroundTasks.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.TaskManagement.Application.Contracts\Miwen.Abp.TaskManagement.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.TaskManagement.Application\Miwen.Abp.TaskManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.TaskManagement.Domain.Shared\Miwen.Abp.TaskManagement.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.TaskManagement.Domain\Miwen.Abp.TaskManagement.Domain.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.TaskManagement.EntityFrameworkCore\Miwen.Abp.TaskManagement.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\task-management\Miwen.Abp.TaskManagement.HttpApi\Miwen.Abp.TaskManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\text-templating\Miwen.Abp.TextTemplating.Application.Contracts\Miwen.Abp.TextTemplating.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\text-templating\Miwen.Abp.TextTemplating.Application\Miwen.Abp.TextTemplating.Application.csproj" />
		<ProjectReference Include="..\..\modules\text-templating\Miwen.Abp.TextTemplating.Domain.Shared\Miwen.Abp.TextTemplating.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\text-templating\Miwen.Abp.TextTemplating.Domain\Miwen.Abp.TextTemplating.Domain.csproj" />
		<ProjectReference Include="..\..\modules\text-templating\Miwen.Abp.TextTemplating.EntityFrameworkCore\Miwen.Abp.TextTemplating.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\text-templating\Miwen.Abp.TextTemplating.HttpApi\Miwen.Abp.TextTemplating.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.Webhooks.Core\Miwen.Abp.Webhooks.Core.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.Webhooks.EventBus\Miwen.Abp.Webhooks.EventBus.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.Webhooks.Identity\Miwen.Abp.Webhooks.Identity.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.Webhooks.Saas\Miwen.Abp.Webhooks.Saas.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.WebhooksManagement.Application.Contracts\Miwen.Abp.WebhooksManagement.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.WebhooksManagement.Application\Miwen.Abp.WebhooksManagement.Application.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.WebhooksManagement.Domain.Shared\Miwen.Abp.WebhooksManagement.Domain.Shared.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.WebhooksManagement.Domain\Miwen.Abp.WebhooksManagement.Domain.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.WebhooksManagement.EntityFrameworkCore\Miwen.Abp.WebhooksManagement.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.WebhooksManagement.HttpApi\Miwen.Abp.WebhooksManagement.HttpApi.csproj" />
		<ProjectReference Include="..\..\modules\webhooks\Miwen.Abp.Webhooks\Miwen.Abp.Webhooks.csproj" />
	</ItemGroup>

</Project>
