<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.Identity.OrganizaztionUnits</AssemblyName>
		<PackageId>Miwen.Abp.Identity.OrganizaztionUnits</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\framework\authorization\Miwen.Abp.Authorization.OrganizationUnits\Miwen.Abp.Authorization.OrganizationUnits.csproj" />
		<ProjectReference Include="..\Miwen.Abp.Identity.Domain\Miwen.Abp.Identity.Domain.csproj" />
	</ItemGroup>

</Project>
