<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Platform.Theme.VueVbenAdmin</AssemblyName>
		<PackageId>Miwen.Platform.Theme.VueVbenAdmin</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
		<PackageReference Include="Volo.Abp.SettingManagement.Domain" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\Miwen.Platform.Application.Contracts\Miwen.Platform.Application.Contracts.csproj" />
		<ProjectReference Include="..\Miwen.Platform.Domain\Miwen.Platform.Domain.csproj" />
		<ProjectReference Include="..\Miwen.Platform.Settings.VueVbenAdmin\Miwen.Platform.Settings.VueVbenAdmin.csproj" />
	</ItemGroup>

</Project>
