<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.Identity.Session.AspNetCore</AssemblyName>
		<PackageId>Miwen.Abp.Identity.Session.AspNetCore</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<!--<ProjectReference Include="..\..\..\framework\common\Miwen.Abp.IP2Region\Miwen.Abp.IP2Region.csproj" />-->
		<ProjectReference Include="..\..\..\framework\common\Miwen.Abp.IP2Region\Miwen.Abp.IP2Region.csproj" />
		<ProjectReference Include="..\Miwen.Abp.Identity.Session\Miwen.Abp.Identity.Session.csproj" />
	</ItemGroup>

</Project>
