<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.Elsa.Activities.Webhooks</AssemblyName>
		<PackageId>Miwen.Abp.Elsa.Activities.Webhooks</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\webhooks\Miwen.Abp.Webhooks\Miwen.Abp.Webhooks.csproj" />
		<ProjectReference Include="..\Miwen.Abp.Elsa\Miwen.Abp.Elsa.csproj" />
	</ItemGroup>

</Project>
