<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<TargetFramework>net8.0</TargetFramework>
		<AssemblyName>Miwen.Abp.OAuth</AssemblyName>
		<PackageId>Miwen.Abp.OAuth</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Miwen\Abp\OAuth\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Miwen\Abp\OAuth\Localization\Resources\*.json" />
	</ItemGroup>

	
	<ItemGroup>
		<!--TODO 只会再添加Feature配置<PackageReference Include="Volo.Abp.Features" />-->
		<PackageReference Include="Volo.Abp.Caching" />
		<PackageReference Include="Volo.Abp.Localization" />
		<PackageReference Include="Volo.Abp.Settings" />
	</ItemGroup>
	
	
</Project>
