<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

		<PropertyGroup>
			<Nullable>enable</Nullable>
			<TargetFramework>net10.0</TargetFramework>
			<AssemblyName>Miwen.Abp.Auditing.HttpApi</AssemblyName>
			<PackageId>Miwen.Abp.Auditing.HttpApi</PackageId>
			<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
			<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
			<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
			<RootNamespace />
		</PropertyGroup>

		<ItemGroup>
			<PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
		</ItemGroup>

		<ItemGroup>
			<ProjectReference Include="..\Miwen.Abp.Auditing.Application.Contracts\Miwen.Abp.Auditing.Application.Contracts.csproj" />
		</ItemGroup>

</Project>
