<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.Saas.Domain</AssemblyName>
		<PackageId>Miwen.Abp.Saas.Domain</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AutoMapper" />
		<PackageReference Include="Volo.Abp.Caching" />
		<PackageReference Include="Volo.Abp.Ddd.Domain" />
		<PackageReference Include="Volo.Abp.Features" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\framework\tenants\Miwen.Abp.MultiTenancy.Editions\Miwen.Abp.MultiTenancy.Editions.csproj" />
	  <ProjectReference Include="..\Miwen.Abp.Saas.Domain.Shared\Miwen.Abp.Saas.Domain.Shared.csproj" />
	</ItemGroup>

</Project>
