<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AssemblyName>Miwen.Abp.Features.LimitValidation.Redis.Client</AssemblyName>
		<PackageId>Miwen.Abp.Features.LimitValidation.Redis.Client</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
		<Description>功能限制验证组件Redis客户端格式实现</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Miwen.Abp.Features.LimitValidation.Redis\Miwen.Abp.Features.LimitValidation.Redis.csproj" />
	</ItemGroup>

</Project>
